services:
  account:
    build:
      context: .
      dockerfile: ./account/Dockerfile
    depends_on:
      - account_db
    environment:
      - DATABASE_URL=postgres://postgres:password@account_db:5432/postgres?sslmode=disable
    networks:
      - my-network
    restart: on-failure

  account_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - my-network
    restart: unless-stopped

  catalog:
    build:
      context: .
      dockerfile: ./catalog/Dockerfile
    depends_on:
      - catalog_db
    environment:
      - DATABASE_URL=http://catalog_db:9200
    networks:
      - my-network
    restart: on-failure

  catalog_db:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - my-network

  order:
    build:
      context: .
      dockerfile: ./order/Dockerfile
    depends_on:
      - order_db
    environment:
      - DATABASE_URL=postgres://postgres:password@order_db:5432/postgres?sslmode=disable
      - ACCOUNT_SERVICE_URL=account:8080
      - CATALOG_SERVICE_URL=catalog:8080
    networks:
      - my-network
    restart: on-failure

  order_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    networks:
      - my-network
    restart: unless-stopped

  graphql:
    build:
      context: .
      dockerfile: ./graphql/Dockerfile
    depends_on:
      - account
      - catalog
      - order
    environment:
      - ACCOUNT_SERVICE_URL=account:8080
      - CATALOG_SERVICE_URL=catalog:8080
      - ORDER_SERVICE_URL=order:8080
    ports:
      - "8000:8080"
    networks:
      - my-network
    restart: on-failure

networks:
  my-network:
    driver: bridge