services:
  account:
    build:
      context: .
      dockerfile: ./account/app.dockerfile
    depends_on:
      - account_db
    environment:
      - DATABASE_URL=postgres://postgres:password@account_db:5432/postgres?sslmode=disable
    restart: on-failure

  account_db:
    build:
      context: .
      dockerfile: ./account/db.dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
    restart: unless-stopped

  catalog:
    build:
      context: .
      dockerfile: ./catalog/app.dockerfile
    depends_on:
      - catalog_db
    environment:
      - DATABASE_URL=http://catalog_db:9200
    restart: on-failure

  catalog_db:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - discovery.type=single-node

  order:
    build:
      context: .
      dockerfile: ./order/app.dockerfile
    depends_on:
      - order_db
    environment:
      - DATABASE_URL=postgres://postgres:password@order_db:5432/postgres?sslmode=disable
      - ACCOUNT_SERVICE_URL=account:8080
      - CATALOG_SERVICE_URL=catalog:8080
    restart: on-failure

  order_db:
    build:
      context: .
      dockerfile: ./order/db.dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
    restart: unless-stopped

  graphql:
    build:
      context: .
      dockerfile: ./graphql/app.dockerfile
    depends_on:
      - account
      - catalog
      - order
    environment:
      - ACCOUNT_SERVICE_URL=account:8080
      - CATALOG_SERVICE_URL=catalog:8080
      - ORDER_SERVICE_URL=order:8080
    ports:
      - "8000:8080"
    restart: on-failure
